apiVersion: apps/v1 
kind: Deployment
metadata:
  name: youtube-clone
  namespace: default
  labels:
    app: yt-clone
spec:
  selector:
    matchLabels:
      app: yt-clone
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yt-clone
    spec:
      containers:
      - name: youtube-clone-container
        imagePullPolicy: Always
        image: merch7x/dev-repo:youtube_clone-v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 500Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        ports:
        - containerPort:  80
      restartPolicy: Always

