apiVersion: v1
kind: Service
metadata:
  name: youtube-clone-svc
  namespace: default
spec:
  selector:
    app: yt-clone
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30008